version: '3.8'

services:
  db:
    image: postgres:14.15-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=clcrud
      - POSTGRES_PASSWORD=clcrud
      - POSTGRES_DB=clcrud
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "clcrud"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        sleep 10 && 
        python manage.py makemigrations && 
        python manage.py migrate && 
         gunicorn app.wsgi:application --bind 0.0.0.0:5000"
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      - ./.env
    networks:
      - app_network
    depends_on:
      - db
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge
