version: '3.8'

services:
  db:
    image: postgres:14.15-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=clcrud
      - POSTGRES_PASSWORD=clcrud
      - POSTGRES_DB=clcrud
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    networks:
      - app_network
    depends_on:
      - db
      
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
